# Generated by Django 4.2.27 on 2025-12-24 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_tabletemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletemplate',
            name='column_mapping',
            field=models.JSONField(help_text="Словарь: {'имя_столбца_в_бд': 'подпись_поля', ...}. Например: {'last_name': 'ФАМИЛИЯ', 'first_name': 'ИМЯ', 'dob': 'ДАТА РОЖДЕНИЯ'}"),
        ),
        migrations.AlterField(
            model_name='tabletemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, который создал шаблон.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tabletemplate',
            name='table_name',
            field=models.CharField(help_text="Имя таблицы в базе данных (например, 'my_table_name').", max_length=255, unique=True),
        ),
    ]
