# Generated by Django 4.2.27 on 2025-12-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tabletemplate_column_mapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabletemplate',
            name='column_mapping',
        ),
        migrations.AddField(
            model_name='tabletemplate',
            name='default_result_fields_order',
            field=models.JSONField(blank=True, default=list, help_text="Список: ['имя_столбца1', 'имя_столбца2', ...] - порядок полей вывода."),
        ),
        migrations.AddField(
            model_name='tabletemplate',
            name='default_search_fields_order',
            field=models.JSONField(blank=True, default=list, help_text="Список: ['имя_столбца1', 'имя_столбца2', ...] - порядок полей поиска."),
        ),
        migrations.AddField(
            model_name='tabletemplate',
            name='result_fields_config',
            field=models.JSONField(blank=True, default=dict, help_text="Словарь: {'имя_столбца_в_бд': 'подпись_для_вывода', ...}. Например: {'last_name': 'Фамилия', 'first_name': 'Имя'}"),
        ),
        migrations.AddField(
            model_name='tabletemplate',
            name='search_fields_config',
            field=models.JSONField(blank=True, default=dict, help_text="Словарь: {'имя_столбца_в_бд': 'подпись_для_поиска', ...}. Например: {'last_name': 'ФАМИЛИЯ', 'first_name': 'ИМЯ'}"),
        ),
    ]
