"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import ldap
# Импортируем как LDAPSearch, так и NestedGroupOfNamesType
from django_auth_ldap.config import LDAPSearch, NestedGroupOfNamesType
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Используем config для SECRET_KEY из .env
SECRET_KEY = config('SECRET_KEY', default='django-insecure-z$faw)&!#7is@mzw5^%e9u9t3u#uh5*wo#pthqv!h8w-glyv%m')

# SECURITY WARNING: don't run with debug turned on in production!
# Используем config для DEBUG из .env, приводим к bool
DEBUG = config('DEBUG', default=True, cast=bool)

# Используем config для ALLOWED_HOSTS из .env, разбиваем строку по запятым
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,0.0.0.0,172.24.1.139', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'auth_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='flintdbf'), # Используем config
        'USER': config('DB_USER', default='pgadmin'), # Используем config
        'PASSWORD': config('DB_PASSWORD'), # Используем config
        'HOST': config('DB_HOST', default='192.168.0.150'), # Используем config
        'PORT': config('DB_PORT', default='5432', cast=str), # Используем config
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'
# Убираем дубликат USE_I18N
USE_I18N = True
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Аутентификация ---
AUTHENTICATION_BACKENDS = [
    'django_auth_ldap.backend.LDAPBackend', # ADDS бэкенд
    'django.contrib.auth.backends.ModelBackend', # Стандартный бэкенд (на всякий случай)
]

LOGIN_URL = '/login/' # URL для страницы входа

# --- Настройки LDAP / Active Directory ---

# Адрес вашего контроллера домена LDAP (из .env)
AUTH_LDAP_SERVER_URI = config('LDAP_SERVER_URI')

# Учетные данные для привязки (биндинга) к AD (сервисная учетная запись, из .env)
AUTH_LDAP_BIND_DN = config('LDAP_BIND_DN')
AUTH_LDAP_BIND_PASSWORD = config('LDAP_BIND_PASSWORD')

# Где искать пользователей (из .env)
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    config('LDAP_USER_SEARCH_BASE'),
    ldap.SCOPE_SUBTREE,
    config('LDAP_USER_SEARCH_FILTER')
)

# Где искать группы (из .env)
AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    config('LDAP_GROUP_SEARCH_BASE'),
    ldap.SCOPE_SUBTREE,
    "(objectClass=group)" # Фильтр для поиска групп
)

# Тип группы (NestedGroupOfNamesType для AD)
AUTH_LDAP_GROUP_TYPE = NestedGroupOfNamesType(name_attr="cn")

# Сопоставление членства в группах AD с флагами пользователя Django (опционально)
# AUTH_LDAP_USER_FLAGS_BY_GROUP = {
#     "is_active": "cn=active_users,ou=groups,dc=example,dc=com",
#     "is_staff": config('LDAP_GROUP_MAPPING_STAFF'),
#     "is_superuser": config('LDAP_GROUP_MAPPING_SUPERUSER'),
# }

# Разрешить Django искать права (permissions) через членство в группах AD
AUTH_LDAP_FIND_GROUP_PERMS = True

# Зеркалировать (отражать) группы AD как группы Django (опционально)
AUTH_LDAP_MIRROR_GROUPS = True

# --- /Настройки LDAP / Active Directory ---
